/*
 * generated by Xtext 2.27.0
 */
package nl.tue.dsldesign.robot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import nl.tue.dsldesign.robot.RobotRuntimeModule;
import nl.tue.dsldesign.robot.RobotStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RobotIdeSetup extends RobotStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RobotRuntimeModule(), new RobotIdeModule()));
	}
	
}
