/*
 * generated by Xtext 2.27.0
 */
package nl.tue.dsldesign.robot.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class RobotProposalProvider extends AbstractRobotProposalProvider {
}
