/*
 * generated by Xtext 2.27.0
 */
package nl.tue.dsldesign.robot;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RobotRuntimeModule extends AbstractRobotRuntimeModule {
}
