/*
 * generated by Xtext 2.27.0
 */
package nl.tue.dsldesign.robot.ui;

import com.google.inject.Injector;
import nl.tue.dsldesign.robot.ui.internal.RobotActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RobotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RobotActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RobotActivator activator = RobotActivator.getInstance();
		return activator != null ? activator.getInjector(RobotActivator.NL_TUE_DSLDESIGN_ROBOT_ROBOT) : null;
	}

}
