/*
 * generated by Xtext 2.27.0
 */
package nl.tue.dsldesign.robot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotScopeProvider extends DelegatingScopeProvider {
}
