/*
 * generated by Xtext 2.27.0
 */
package nl.tue.dsldesign.robot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RobotUiModule extends AbstractRobotUiModule {

	public RobotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
